services:
  postgres:
    image: postgres:15.3-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: outbox
      POSTGRES_PASSWORD: outbox
      POSTGRES_DB: outbox
    ports:
      - "5445:5432"
    volumes:
      - outbox_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U outbox -d outbox"]
      interval: 5s
      timeout: 5s
      retries: 10

  pulsar:
    image: apachepulsar/pulsar:3.1.0
    container_name: nest-outbox-pulsar
    command: bin/pulsar standalone
    ports:
      - "6650:6650"
      - "8080:8080"
    healthcheck:
      test: ["CMD", "bin/pulsar-admin", "brokers", "healthcheck"]
      interval: 5s
      timeout: 5s
      retries: 30

volumes:
  outbox_pgdata:
